# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.187.0/containers/cpp/.devcontainer/base.Dockerfile

# [Choice] Debian / Ubuntu version: debian-10, debian-9, ubuntu-20.04, ubuntu-18.04
ARG VARIANT="debian-11"
FROM mcr.microsoft.com/vscode/devcontainers/cpp:0-${VARIANT}

# Install MongoDB command line tools if on buster and x86_64 (arm64 not supported)
ARG MONGO_TOOLS_VERSION=4.4
# [Optional] Uncomment this section to install additional packages.
RUN  curl -sSL "https://www.mongodb.org/static/pgp/server-${MONGO_TOOLS_VERSION}.asc" | gpg --dearmor > /usr/share/keyrings/mongodb-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg] http://repo.mongodb.org/apt/debian buster/mongodb-org/${MONGO_TOOLS_VERSION} main" | tee /etc/apt/sources.list.d/mongodb-org-${MONGO_TOOLS_VERSION}.list \
          && apt-get update && export DEBIAN_FRONTEND=noninteractive \
          && apt-get install -y mongodb-org-server mongodb-org-shell \
          && apt-get -y install --no-install-recommends icu-devtools \
               clang-format \
               clang-tidy \
               libboost-all-dev \
               libssl-dev \
               openssl \
               cmake-curses-gui \
               python3-pip \
          && apt-get clean -y && rm -rf /var/lib/apt/lists/*; 

RUN pip install conan
